name: SkyblockCore
version: 1.0
author: Farmeurimmo
main: fr.farmeurimmo.verymc.core.Main
depend: [Citizens, IridiumSkyblock, HolographicDisplays, Vault]
api-version: 1.16
commands:
  spawn:
  build:
  farm2win:
    aliases: [boutiqueig]
  bar:
  menu:
  warp:
  warps:
  featherfly:
  dailyfly:
  itemleg:
  fly:
  feed:
  hat:
  craft:
  enchantement:
    aliases: [ench]
  gm:
  gma:
  gmc:
  gmsp:
  gms:
  afkmine:
  checkfly:
  invsee:
  redstone:
  tpa:
  tpacancel:
  tpyes:
  tpno:
  challenges:
    aliases: [c]
  atout:
    aliases: [atouts]
  datafile:
  key:
  money:
  pay:
  baltop:
  shop:
  sellall:
  chests:
  