name: SkyblockCore
version: 1.0
author: Farmeurimmo
main: fr.farmeurimmo.criptmania.Main
depend: [Citizens, TheNewEconomy, IridiumSkyblock]
api-version: 1.16
commands:
  spawn:
  wiki:
  build:
  farm2win:
    aliases: [boutiqueig]
  bar:
  menu:
  warp:
  warps:
  featherfly:
  dailyfly:
  itemleg:
  fly:
  feed:
  hat:
  craft:
  enchantement:
    aliases: [ench]
  gm:
  gma:
  gmc:
  gmsp:
  gms:
  afkmine:
  ss:
    aliases: [sanctionset]
  checkfly:
  invsee:
  redstone:
  tpa:
  tpacancel:
  tpyes:
  tpno:
  challenges:
    aliases: [c]
  atout:
    aliases: [atouts]
  