name: SkyblockCore
version: 1.0
author: Farmeurimmo
authors:
  - Farmeurimmo
main: main.java.fr.verymc.spigot.Main
depend: [ Citizens, HolographicDisplays, LuckPerms ]
api-version: 1.16
commands:
  spawn:
  build:
    permission: build
  farm2win:
    aliases: [ boutiqueig,f2w ]
  bar:
    permission: bar
  menu:
  warp:
  warps:
  featherfly:
    permission: featherfly.give
  dailyfly:
    permission: dailyfly
  itemleg:
    permission: itemleg
  fly:
    permission: fly
  feed:
    permission: feed
  hat:
    permission: hat
  craft:
    permission: craft
  enchantement:
    aliases: [ ench ]
    permission: enchantement
  gm:
    permission: gm
  gma:
    permission: gma
  gmc:
    permission: gmc
  gmsp:
    permission: gmsp
  gms:
    permission: gms
  afkmine:
    permission: afkmine
  checkfly:
    permission: checkfly
  tpa:
  tpacancel:
  tpyes:
  tpno:
  challenges:
    aliases: [ c ]
  atout:
    aliases: [ atouts ]
  datafile:
    permission: datam
  key:
    permission: key.admin
  money:
  pay:
  baltop:
  shop:
  sellall:
    permission: sellall
  chests:
    permission: chests.give
  farmhoe:
    permission: farmhoe.give
  pickaxe:
    permission: pickaxe.give
  reboot:
    permission: reboot
  ah:
    permission: ah
  events:
    permission: events
  admin:
    permission: admin.manage
  minions:
    permission: minions.manage
  is:
  invest:
  playerwarp:
  claim:
  trade:
    permission: trade
  tradeyes:
    permission: trade
  tradeno:
    permission: trade
  tradecancel:
    permission: trade
  dungeonadmin:
    permission: dungeon.admin
